In [1]:
import matplotlib.pyplot as plt
class dataanalysis:
    def __init__(self, data):
        self.data = data
    def sum_of_data(self):
        return sum(self.data)
    def data_doubled(self):
        return [2 * element for element in self.data]
    def plot_data_histogram(self):
        plt.bar(range(len(self.data)), self.data, edgecolor='black')
        plt.title('histogram of data elements')
        plt.xlabel('index')
        plt.ylabel('data value')
        plt.show()

In [3]:
pip install pandas matlotlib.py numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matlotlib.py (from versions: none)
ERROR: No matching distribution found for matlotlib.py


In [4]:
pip install pandas matplotlib

^C
Note: you may need to restart the kernel to use updated packages.


  Using cached pandas-2.3.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 2.2 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.0 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.0 MB 2.7 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.0 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.0 MB 2.7 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/11.0 MB 2.8 MB/s eta 0:00:03
   ------------------ --------------------- 5.0/11.0 MB 3.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.8/11.0 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.0 MB 3.3 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.0 MB 3.4 MB/s eta 0:00:01
   ----------------

In [5]:
import matplotlib.pyplot as plt

In [6]:
import matplotlib.pyplot as plt
class dataanalysis:
    def __init__(self, data):
        self.data = data
    def sum_of_data(self):
        return sum(self.data)
    def data_doubled(self):
        return [2 * element for element in self.data]
    def plot_data_histogram(self):
        plt.bar(range(len(self.data)), self.data, edgecolor='black')
        plt.title('histogram of data elements')
        plt.xlabel('index')
        plt.ylabel('data value')
        plt.show()

In [7]:
import numpy as np
ratings = np.array([[94, 89, 63, 45], [93, 92, 48, 23], [92, 94, 56, 98]])
print(ratings)

[[94 89 63 45]
 [93 92 48 23]
 [92 94 56 98]]


In [8]:
import numpy as np
population_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])
print(population_data)

[[45 65 70]
 [55 60 50]
 [60 58 67]]


In [9]:
import pandas as pd
list_df = [[32, 'portugal' , 94], [30, 'Argentina' , 93], [25 , 'Brazil' , 92]]
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']
columns = ['age', 'nationality', 'overall']
pd.DataFrame(data=list_df, index=index, columns=columns)

age nationality  overall
Christiano Ronaldo   32    portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92